tasks/task/urls.py
from django.urls import path

from . import views

app_name = 'task'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
  
]

tasks/tasks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include("task.urls")),]

tasks/task/models.py
from django.db import models

# Create your models here.

tasks/task/views.py
from django import forms
from django.http import  HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse



class NewTaskForm(forms.Form):
    task = forms.CharField(label='New Task')
    
# Create your views here.
def index(request):
   if "tasks" not in request.session:
    request.session["tasks"] = []
    return render(request, "task/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.valid():
            tasks = form.cleaned_data["task"]
            request.session["tasks"] +=[task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request, "task/add.html", {
                "form": form
            })
    return render(request, "task/add.html", {
        "form": NewTaskForm()
        
    })

tasks/task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
        <h1>Add Task</h1>
    <form action="{% url 'task:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'task:index' %}">Tasks</a>
{% endblock %}

tasks/task/templates/task/index.html
{% extends "task/layout.html" %}

{% block body %}
    <h1> Add Tasks</h1>
    <ul>
    {% for task in tasks %}
            <li>{{ task }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'task:add' %}">Add Task</a>
{% endblock %}

tasks/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>taskst</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>